before_script:
  - docker info

build_image:
  stage: build
  script:
    - docker build . -t docker.maxiv.lu.se/maint
    - docker push docker.maxiv.lu.se/maint
  only:
    - master

deploy_image:
  stage: deploy
  script:
  - "curl -H 'Authorization: Bearer gOj9o8s3RapHiThfNbImaFYMDoOKTG' -k --request POST https://ansible.maxiv.lu.se/api/v2/job_templates/13/launch/"
  only:
    - master

build_image_develop:
  stage: build
  script:
    - docker build . -t docker.maxiv.lu.se/maint-test
    - docker push docker.maxiv.lu.se/maint-test
  only:
    - develop

deploy_image_develop:
  stage: deploy
  script:
  - 'curl -H "Authorization: Bearer $AWX_TOKEN" -XPOST https://ansible.maxiv.lu.se/api/v2/job_templates/28/launch/'
  only:
    - develop
